#!/bin/sh

### BEGIN INIT INFO
# Provides:          root
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:    Cassandra
# Description:          Cassandra
### END INIT INFO

# System binaries
SU=/bin/su
TOUCH=/bin/touch

NAME=$( basename -- $0 )
DESC="Aperasco-ui"

APE_ROOT=/home/vagrant/apache-ui
APE_USER=root

START_DAEMON=${APE_ROOT}
STOP_DAEMON=${APE_ROOT}/bin/stop-server

LOCK_FILE=/var/run/${NAME}.lock

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

do_start()
{
    echo "Starting ${NAME}: ${DESC}"
    
    if [ -f "${LOCK_FILE}" ];
    then
    echo "Lock file exists - ${DESC} is running already?"
    exit 1
    else
    cd ${START_DAEMON}
    ${SU} ${APE_USER} -c play start
    ${TOUCH} ${LOCK_FILE}
    fi
}

do_stop()
{
    echo "Stopping ${NAME}: ${DESC}"
    ${SU} ${APE_USER} -c ${STOP_DAEMON}
    rm -f ${LOCK_FILE}
}

do_restart()
{
    do_stop
    do_start
}

case "$1" in

    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart)
        do_restart
        ;;
    *)
        echo "Usage: ${NAME} {start|stop|restart}"
        exit 1
        ;;

esac

exit 0

